### ISSUE TITLE
how can I make labels into useful data

### ISSUE THREAD

**Issue by GaelGil** [GaelGil/notebooks#13]
So I have a pandas dataframe that looks like this 
* **Class** 
* Iris-versicolor
* Iris-setosa
* Iris-versicolor
* Iris-setosa
* Iris-virginica

What I want to do is apply a function where I can turn these labels into numeric useful values. That would look like this:
class -- iris_versicolor -- iris_setosa -- iris_versicolor,
Iris-versicolor -- 1 -- 0 -- 0
Iris-setosa -- 0 -- 1 -- 0
Iris-versicolor -- 0 -- 0 -- 1

I did this once but I cant seem to find where how to do it.

**Comment by camoverride** [comment]
If you have some data like this:

| species |
| iris-setosa |
| iris-setosa |
| iris-versicolor |
| iris-setosa |
| iris-versicolor |

You can turn it into *dummy variables* like this:

| dummy_1 | dummy_2 |
| 1 | 0 |
| 1 | 0 |
| 0 | 1 |
| 1 | 0 |
| 0 | 1 |

where the number of dummy columns is equal to the number of unique values in the original *species* column. Obviously this isn't useful when there are lots and lots of unique values.

**Comment by GaelGil** [comment]
I am closing this issue since I have implemented this into the notebook.
