### ISSUE TITLE
Comparing books

### ISSUE THREAD

**Issue by GaelGil** [GaelGil/notebooks#25]
I am trying to compare two book genres. The genres are cookbooks and gothic/horror novels. The way in which I am doing this is I have a csv file containing storing each book. All the words to a book are in a column called `words`. The data can be found [here](https://github.com/GaelGil/notebooks/blob/master/book_genre_detection/data.csv). I am trying to embed each of these books. So I can then compare them to other books and later on graph them. I have some code written [here](https://github.com/GaelGil/notebooks/blob/master/book_genre_detection/book_comparison.ipynb) but I am also not sure what it is doing exactly. 

If I am not mistaken these lines here embeds my text:

~~~python
text = "This is my sample sentence"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output.last_hidden_state
~~~
So `encoded_input.last_hidden_state` would be my vector that I can use to compare to others and use to graph? 

Another thing I was wondering about is `tokenizer` only takes input length of 512. Since I am using whole books would I have to extract the sentences of each book and embed those to create one huge vector that represents a book and the vectors inside are sentences?

**Comment by camoverride** [comment]
Let's say you have a document like this and want to embed it:

```
It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.
```

An embedding algorithm like BERT is going to accept a fixed-length vector of _numbers_, where each number indexes a unique dictionary entry. For instance, "dog" might be __5__ and "lasagna" might be __8237__. So the first thing that will happen is that your document is transformed into a list of indexes. The phrase "dog lasagna" is translated into the array `[5, 8237]`.

BERT accepts a fixed-length array, usually 512 elements long but different flavors of the model accept different lengths. To get around the fact that your "sentence" is only 2 elements long ("dog lasagna" = `[5, 8237]`), you just add padding to get it to the right length: `[5, 8237, 0, 0, 0, 0, 0, 0, ..., 0]`

When you put this "padded" vector through BERT, you get a tensor as output. That tensor has 512 elements, of which the final 510 are the embeddings for `0`, which are useless and you can ignore. You only need to worry about the embeddings for the two words in the phrase.

The next question is: what do I do with these word embeddings? Maybe average them together to get a "phrase/sentence embedding". Then maybe average together all the sentences in your document to get a "document embedding" (which is your ultimate goal here). However, consider the computational cost here. If you are trying to get a document embedding for a long document, like an entire novel, do you think it makes more sense to embed the entire thing, or maybe to sample some random sentences from throughout the book? Maybe it will take a very long time to embed every sentence.

**Comment by camoverride** [comment]
Also, if you want to see some instant results, don't bother embedding entire books right now. Here's what you can do. Try and embed 5 "positive" words and 5 "negative" words and then compare the vectors. For instance:

- kill, hurt, sad, angry, tired
- happy, funny, smart, sunshine, vacation

Get the vectors for these two categories of words. Then reduce each vector down to 2 dimensions using t-SNE or PCA. Plot your 2-d vectors. See if the negative and positive words cluster together. If a visual inspection isn't enlightening, think of some mathematical way to test whether these words are "randomly distributed across vector space" or cluster together somehow

**Comment by camoverride** [comment]
If you're using the pandas library, your dataframe might look like this:

| word      | embedding  | 2d-embedding |
| ----------- | ----------- |-------------|
| love      | [0.9, 0.343, 0.565, ..., 0.733]       | [0.14, 0.03] |
| hate   | [0.56, 0.989, 0.123, ..., 0.409]        | [0.897, 0.75] |

**Comment by GaelGil** [comment]
I have learned the basics of bert and gotten some embeddings from words. I have also been able to graph the 2d embeddings. This can be found here.
